### ISSUE TITLE
Result of SteamApi.GetAchievements(game.GameId, SteamApi.CurrentAccountInfos) doesn't contain completion info, when no API-Key is set

### ISSUE THREAD

**Issue by AgentRocket** [Lacro59/playnite-plugincommon#108]
This is a continuation of https://github.com/Lacro59/playnite-successstory-plugin/issues/444

SteamApi.CurrentAccountInfos returns null, if no API-Key is set. This results in the code at https://github.com/Lacro59/playnite-plugincommon/blob/95b985867adc9ae54b043ad3d13a4be733637474/CommonPluginsStores/Steam/SteamApi.cs#L424-L456 not being executed and no completion Info being added to the achievements.

**Comment by Lacro59** [comment]
Done
