### ISSUE TITLE
(via CheckDLC) Steam not authenticated (see also https://github.com/Lacro59/playnite-checkdlc-plugin/issues/86)

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-plugincommon#130]
Cross Reference https://github.com/Lacro59/playnite-checkdlc-plugin/issues/86

Sorry, if I open this ticket, which duplicates the mentiond issue, but I have a gut feeling that CheckDLC just needs a rebuild release to fix that issue, that the Steam Auth doesn't work in that plugin?

And why does it even need an extra authentication?

**Comment by joyrider3774** [comment]
> And why does it even need an extra authentication?

because i think crow once said he did not like plugins having access to the libraries authentication data

**Comment by joshfigueroa** [comment]
As the error is occurring in the GetJsonInString() function, I inspected the function at [playnite-plugincommon](https://github.com/Lacro59/playnite-plugincommon/tree/master)/[CommonPluginsShared](https://github.com/Lacro59/playnite-plugincommon/tree/master/CommonPluginsShared)/Tools.cs (Lines 180 - 210)

`[Obsolete]
        public static string GetJsonInString(string str, string strStart, string strEnd, string strPurge = "")
        {
            try
            {
                int indexStart = str.IndexOf(strStart);
                int indexEnd = str.IndexOf(strEnd);

                string stringStart = str.Substring(0, indexStart + strStart.Length);
                string stringEnd = str.Substring(indexEnd);

                int length = str.Length - stringStart.Length - stringEnd.Length;

                string JsonDataString = str.Substring(indexStart + strStart.Length, length);

                if (!strPurge.IsNullOrEmpty())
                {
                    indexEnd = JsonDataString.IndexOf(strPurge);
                    length = JsonDataString.Length - (JsonDataString.Length - indexEnd - strPurge.Length + 1);
                    JsonDataString = JsonDataString.Substring(0, length);
                }

                return JsonDataString;
            }
            catch (Exception ex)
            {
                Common.LogError(ex, false);
            }

            return string.Empty;
        }`

It appears that the function checkdlc is calling is obsolete, and there is a newer function available at line 212. Is it possible to remove this obsolete function to solve the issue?
